### ISSUE TITLE
dial tcp 127.0.0.1:8089: connect: connection refused

### ISSUE THREAD

**Issue by hsiangawang** [ContainerSolutions/locust_exporter#6]
When I open the `http://localhost:9646/metrics`, I found that locust_up is 0
Then I check the log and find this error message
![截圖 2020-07-02 上午11 39 54](https://user-images.githubusercontent.com/37170106/86313928-e9919e80-bc58-11ea-99f9-c2164fbb54a3.png)

My docker-compose file:

![截圖 2020-07-02 上午11 44 14](https://user-images.githubusercontent.com/37170106/86314128-6d4b8b00-bc59-11ea-9219-7348e5973584.png)

What would be the possible reason for this problem?

**Comment by pperzyna** [comment]
By default, Locust Exporter tries to connect to `http://localhost:8089`, but in your case, the URL of the master is `http://master:8089`. So, You have to set the environmental variable called `LOCUST_EXPORTER_URI` up. 

```yaml
  locust-exporter:
    image: containersol/locust_exporter
    environment:
      - LOCUST_EXPORTER_URI=http://master:8089
    ports:
      - 9646:9646
    depends_on:
      - master
```
